title: NEAR Documentation
email: gagdiez.c@gmail.com
description: A complete tutorial on developing NEAR smartcontracts
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: gagdiez
github_username:  gagdiez

# Build settings
theme: "just-the-docs"
remote_theme: pmarsceill/just-the-docs

# Just the docs config
search_enabled: false

# Define Jekyll collections
collections:
  # Define a collection named "docs", its documents reside in the "_docs" directory
  docs:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    docs:  # Reference the "docs" collection
      name: Documentation
      nav_exclude: false
      search_exclude: false
